---
version: '3.8'
networks:
    datapipeline:

services: 
  hazelcast-1:
    build: ./hazelcast
    container_name: hazelcast-1
    ports:
      - '5701:5701'
    environment:
      HZ_CLUSTERNAME: logs
    networks:
      - datapipeline

  hazelcast-2:
    build: ./hazelcast
    container_name: hazelcast-2
    ports:
      - '5702:5701'
    environment:
      HZ_CLUSTERNAME: logs
    networks:
      - datapipeline

  hazelcast-3:
    build: ./hazelcast
    container_name: hazelcast-3
    ports:
      - '5703:5701'
    environment:
      HZ_CLUSTERNAME: logs
    networks:
      - datapipeline

  task-1:
    build:
      ./task-1
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline


  without-1:
    build:
      ./client_1
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline

  without-2:
    build:
      ./client_1
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline

  without-3:
    build:
      ./client_1
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline

  pesimistic-1:
    build:
      ./client_2
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline

  pesimistic-2:
    build:
      ./client_2
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline

  pesimistic-3:
    build:
      ./client_2
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline

  optimistic-1:
    build:
      ./client_3
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline

  optimistic-2:
    build:
      ./client_3
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline

  optimistic-3:
    build:
      ./client_3
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline


  producer:
    build:
      ./producer
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline

  first_reader:
    build:
      ./first_reader
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline

  second_reader:
    build:
      ./second_reader
    depends_on:
      - hazelcast-3
      - hazelcast-2
      - hazelcast-1
    networks:
      - datapipeline

  management-center:
    image: hazelcast/management-center
    container_name: management-center
    ports:
      - '8080:8080'
    networks:
      - datapipeline